Fix port number ambiguity and path issue
When I read this I was stumped for a while by the fact that the same name was used for what I believe should be two different values. TODO was used for both the ORPort and the obfs4 port.. I tried to make it clear that these should be two different ports. Also, you install obfs4 into /usr/local/bin but then configured tor to use /usr/bin.

Some issues I was unable to resolve:
1. on CentOS Linux release 7.6.1810 I was unable to install obfs4 using 'go get'.
go get gitlab.com/yawning/obfs4.git/obfs4proxy
# cd .; git clone https://gitlab.com/yawning/utls /tmp/tmp.HMbPtKs8RV/src/gitlab.com/yawning/utls.git
error: RPC failed; result=22, HTTP code = 404
fatal: The remote end hung up unexpectedly
package gitlab.com/yawning/utls.git: exit status 128

2. On Fedora 30 I was able to install obfs4, but I struggled with selinux. I needed:
    /sbin/restorecon -v /usr/local/bin/obfs4proxy
    Relabeled /usr/local/bin/obfs4proxy from system_u:object_r:tor_exec_t:s0 to system_u:object_r:bin_t:s0
and
    semanage port -a -t tor_port_t -p tcp 4151
to get things working. I suspect your suggested chcon was ill-advised and resulted in the need for me to run restorecon.